### PR TITLE
KubeJs script cleanup

### PR DESCRIPTION
**Pull request by arc25275**
I started working on cleaning up Kubejs scripts, and separating it by the type of mod that the recipe involves (so far createMilling and createCrushing), as well as associated recipe removals. I also cleaned up / reduced the size of some of the code, but I wanted you to be able let me know if you would like a different style for how it is all organized before I continue too far, so this is a draft pr.

I also added the two largest shaders and resourcepacks (BetterVanillaBuilding and Complimentary Reimagined), as it would take like 30+ seconds to reload packwiz which would  bug out multimc, though the dev has fixed this slow loading since so I could remove it if needed

### CODE REVIEW

**Comment by LizardLeliel** [comment]
Does your editor support easy indentation modification? Can tabs be changed to spaces and set the standard intent width to 4 spaces? It's currently 7 or 8. If it takes more than 4 minutes then don't worry about it, I'll go through that kind of change later another day.

**Comment by arc25275** [comment]
Yeah that wouldn't be a problem I can just add a config for prettier

**Comment by arc25275** [comment]
Create is done! The next mods I'll be separating out and organizing are techreborn and tconstruct, and I'm thinking about separating out different vanilla recipe types as well but I'm not 100% sure yet

**Comment by arc25275** [comment]
Okay I think that this is pretty much ready for review, the only thing that needs to be done is deciding how to implement this. Something that I could do is make this PR be for the experimental branch, and manually make all of the changes that have been made in that new branch so it is easier to merge. Alternatively, this could merge into the main branch and all of those issues with the experimental branch could be dealt with by whoever decides to merge everything

Looking at it now, I think converting the experimental changes to this branch wouldn't be too difficult, a few hours of work at best, so let me know if you would prefer to do that!

**Comment by Laskyyy** [comment]
Reviewing them ingame to check for any possible hiccups, this can likely be merged into main, may isolate the current experimental changes and re-introduce in this format but will wait on that for now, until a possible better method arises.

**Pull request merged**
