### PR TITLE
Ponder

### PR DESCRIPTION
**Pull request by arc25275**
This pull request will add create-styled ponders to aspects of the modpack that are currently confusing to players;

### Tinkers
- [x] Basic how-to on foundry and melter setup
  - Explained basics of heated + melter and faucets, as well as interactions with create pipes

### Create: Astral
- [x] Electrolyser

Added ponder showing all 3 layers, how water needs to be pumped in, oxygen needs to be pumped out, and how the oxygen can be used.

https://user-images.githubusercontent.com/55003876/229992300-0da6e4c5-8ac1-4066-a677-7018159fbf87.mp4

- [ ] Future Multiblock (secret)
- [x] Moon portal

### CODE REVIEW

**Comment by Zarklord** [comment]
I just want to say this video alone did a better job of explaining the electrolyser than the guide did, and it would be awesome for this stuff to be in this modpack.

**Comment by arc25275** [comment]
Looks like thats from probejs. I'll remove it, we should just mention somewhere that people will have to generate their own

**Comment by PIG208** [comment]
This looks amazing. What's the current status of this PR? I would love to help if I can.

**Comment by Erdragh** [comment]
The current problem is that custom machinery uses the same block but with different nbt to differentiate the machines. Create ponders are registered to a block and don't care about NBT. I've started work on a mod that alleviates this issue but haven't gotten it to work yet.

**Comment by Erdragh** [comment]
I'm continuing this in #278. I will close this PR as such.

**Pull request closed without merging**
