### PR TITLE
Mixing spices recipies

### PR DESCRIPTION
**Pull request by RaKonski**

### CODE REVIEW

**Comment by nageih** [comment]
Hi! If you want to register new fluids, please don't forget to add translation keys for them, as mentioned [here](https://github.com/Laskyyy/Create-Astral#contributing)

**Comment by RaKonski** [comment]
Beer

**Comment by Laskyyy** [comment]
Sequenced Recipes don't seem to work on my instance & Filling mug recipes might be using wrong fluids namespaces?

**Comment by RaKonski** [comment]
💀

**Pull request merged**
