### PR TITLE
Farmer's Delight Compat

### PR DESCRIPTION
**Pull request by RandomUser240306**
Adds heated mixing recipes to produce fluid versions of Farmer's Delight cooking pot recipes and spouting recipes to serve the food. Also adds cutting board recipes as sawing recipes.

### CODE REVIEW

**Comment by RandomUser240306** [comment]
Way too many conflicts for the old PR to be of any use

**Comment by Laskyyy** [comment]
Ty, will look to merging after testing ❤️

**Comment by RandomUser240306** [comment]
Modified the code to use ingredients from recipe json instead of KubeJS functions.

**Comment by Laskyyy** [comment]
Verified, looks good to me. I'm going to merge this into experi and perhaps add a small section in the questbook regarding farmers delight automation.

**Pull request merged**
