### PR TITLE
Name tag recipe

### PR DESCRIPTION
**Pull request by Infern0-b0b**
I made a cheap recipe for the vanilla name tag. They are only used for aesthetical purposes and as such they should be inexpensive.

-b0b

### CODE REVIEW

**Comment by Druivenpasta** [comment]
Shouldn't this be a crafting recipe instead? I feel like compacting is not the right recipe type to do this with.

**Comment by Infern0-b0b** [comment]
The reason I had it be a compacting recipe was because I felt that the ink would need pressed into the canvas, but if it seems weird, then I can just change it and will do so.

-b0b

**Comment by Erdragh** [comment]
Isn't the ink/writing only put on the nametags in an anvil?

**Comment by Erdragh** [comment]
You can push another commit onto the branch and it will show up here. That's how Pull Requests work.

**Comment by Laskyyy** [comment]
I swear we had a name tag recipe at one point.

**Pull request merged**
