### PR TITLE
Adding Russian language WIP

### PR DESCRIPTION
**Pull request by ryotochen**
In this pull request I am adding Russian language support for modpack

- [ ] Translate quests
  - [x] Chapter 1
  - [x] Chapter 2
  - [x] Chapter 3
  - [ ] Chapter 4
  - [x] Chapter 5
  - [x] Chapter 6
  - [ ] Chapter 7
  - [ ] Chapter 8
- [ ] Translate all items 
- [x] Feeling tired

### CODE REVIEW

**Comment by AlexMarsev666** [comment]
👍

**Comment by ryotochen** [comment]
I tried to add localization from a more recent version of createaddition. I also translated a large part of the items, but I still need to translate dbe and the remaining quests. I estimate the translation progress to be around 50%, and the quality could be better.

**Comment by Erdragh** [comment]
Once this is ready, please mark the PR as such. I will make it a Draft in the meantime.

**Comment by Laskyyy** [comment]
As of https://github.com/Laskyyy/Create-Astral/pull/389 all the translation keys and 2.1 content has been shuffled around making older translations a little fragmented, unfortunately. I'm going to close PR's for pre-2.1 translations because of this.

**Pull request closed without merging**
