### PR TITLE
Add French trad for FTBquests 

### PR DESCRIPTION
**Pull request by fraigneau**

### CODE REVIEW

**Comment by fraigneau** [comment]
the translation is automated so there may be some small errors

**Comment by fraigneau** [comment]
in the perspective that I find other content to translate I will try to do the best

but I think that for the French-speaking community this should be enough to progress in this adventure with complete confidence

**Comment by WhoPlaysTheFool** [comment]
Franch

**Comment by Erdragh** [comment]
If this is still a WIP, please convert the PR to Draft status

**Comment by fraigneau** [comment]
After proofreading the pull is operational for the French translation 
Valid if you agree

**Comment by Laskyyy** [comment]
As of https://github.com/Laskyyy/Create-Astral/pull/389 all the translation keys and 2.1 content has been shuffled around making older translations a little fragmented, unfortunately. I'm going to close PR's for pre-2.1 translations because of this.

**Pull request closed without merging**
