### PR TITLE
Cleanup and GitHub actions

### PR DESCRIPTION
**Pull request by Erdragh**
This PR does some overdue housekeeping:
- Fixing grammar and spelling mistakes in the README
- setting client side mods to `client`
- more VSCode extension recommendations and default settings
- gitattributes from the packwiz example modpack
- updates to the packwizignore file(s)

And most importantly:
A GitHub action that automatically builds and uploads the client pack. If packwiz fails to export the action will fail and any commit/PR with a failing status will be marked as such.

### CODE REVIEW

**Comment by Erdragh** [comment]
I should clarify: The client pack isn't automatically uploaded to CurseForge or any place like it, it will be uploaded into the artifacts of the specific GitHub Actions run, accessible from the [Actions Tab](https://github.com/Laskyyy/Create-Astral/actions)

**Review by Laskyyy — APPROVED** [review]
Should be good to merge this into experimental.

It may be considered to have auto-actions for commits disabled for now until merging experimental into main for the actual release, if the versions aren't in particularly user-playable states?

**Comment by Erdragh** [comment]
alright, I can do that

**Comment by Erdragh** [comment]
Although, the actions make sure that packwiz can build the repo, which is kind of important. It's not about whether it's playable, it's about whether the included files even work with packwiz

**Pull request merged**
