### PR TITLE
MOON TRAINS

### PR DESCRIPTION
**Pull request by Erdragh**
They're here. Thanks to @ReignOfFROZE and @therobbie73's compat mod we can now drive trains through portals!

I will leave this PR as a draft until it's been proven everything works as expected.

### CODE REVIEW

**Comment by Erdragh** [comment]
Note 1:
Getting disconnected from the train controls after traveling through a portal is _not_ a problem with this compat mod, it also happens with just Create and the Nether.

**Comment by Erdragh** [comment]
Note 2:
The issues with non-standard size portals are caused by CustomPortalAPI itself, not this compat mod. It also happens without trains.

**Comment by ReignOfFROZE** [comment]
Happy to see it's getting used. Enjoy.

**Comment by Erdragh** [comment]
At time of writing no other issues _with the compat mod specifically_ are known to me, so I'll merge this.

**Pull request merged**
