### PR TITLE
Added StarEI -- an REI Addon for astral's Custom Machinery Stuff

### LINKED ISSUE #362: [Feature Request]: Roughly Enough Resources
### Is your feature request related to a problem?

Ever wonder where the modded ores generate most commonly? Or wonder it an item comes as a drop from a block?

### Solution(s)

Roughly Enough Resources displays worldgen data and block drops. It works like how Just Enough Resources did back when it used to be good.

### Describe alternatives you've considered

Just Enough Resources doesn't display ore generation data in 1.18. Don't use it!
Roughly Enough Resources is the only good mod I know of for displaying ore gen data in 1.18

### Additional context

image

### PR DESCRIPTION
**Pull request by mnorfolk03**
Also added some standard REI addons (closes #362 )

Source code for StarEI if you're curious:
https://github.com/mnorfolk03/StarEI

Example StarEI category:
image

Custom Machinery recipes don't all show up at the same time
image

### CODE REVIEW

**Comment by cubebotfan** [comment]
Are there any overlapping tabs between the addons? We might want to remove the duplicate ones

**Comment by cubebotfan** [comment]
I'll test this branch right now an will make a pr if there's anything I can improve

**Comment by cubebotfan** [comment]
I don't know if roughly enough professions is needed since roughly enough trades already shows profession blocks (awkwardly).

The stone growth chamber is also outdated but you should wait until #402 gets merged since the stone growth chamber is changed again in that pr

**Comment by cubebotfan** [comment]
It would be great if we could move the loot tables tab towards the end between mob drops and oregen but idk if it's possible to move rei tabs

**Comment by mnorfolk03** [comment]
> I don't know if roughly enough professions is needed since roughly enough trades already shows profession blocks (awkwardly).
> 
> The stone growth chamber recipes are also outdated but you should wait until #402 gets merged since the stone growth chamber is changed again in that pr

This was made before stone growth chamber got removed. I'll need to update the recipes at some point, but I believe the old recipes are still valid, but I can work on that sometime soon


> It would be great if we could move the loot tables tab towards the end between mob drops and oregen but idk if it's possible to move rei tabs

I don't think I have control over that, I think that's probably an REI thing, but will look into it, and potentially open a future PR if I find a solution (after this is merged)

**Pull request merged**
